groupplanning/urls.py
from django.contrib import admin
from django.urls import include, path

from controlling.views import main as controlling_main

urlpatterns = [
    path("", controlling_main, name="main"),
    path("staffing/", include("staffing.urls")),
    path("projects/", include("projects.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"
urlpatterns = [
    path("", views.index, name="index"),
    path("details/<str:acronym>/", views.details, name="details"),
    path("details/<str:acronym>/staff_budget_item/<int:id>/", views.staff_budget_item, name="staff_budget_item"),
]

staffing/urls.py
from django.urls import path

from . import views

app_name = "staffing"
urlpatterns = [
    path("", views.index, name="index"),
    path("details/<int:staff_id>/", views.details, name="details"),
]

controlling/models.py
from django.db import models

projects/models.py
from django.db import models

EmploymentCategories = {
    'student': 'Studentische Hilfskraft',
    'undergrad': 'Nicht-Wissenschaftliche Mitarbeiter',
    'researcher': 'Wissenschaftliche Mitarbeiter',
}

# Create your models here.
class Project(models.Model):
    acronym = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    extension_planning_date = models.DateField(blank=True, null=True)
    budget_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.acronym

    def get_years(self):
        return [str(i) for i in range(self.start_date.year, self.end_date.year + 1)]

class StaffBudgetItem(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    short_title = models.CharField(max_length=50, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)


    def __str__(self):
        return f"{self.project.acronym} - {self.title}"

    def get_eligibilities(self):
        return StaffBudgetItemEligibility.objects.filter(budget_item=self)

class StaffBudgetItemEligibility(models.Model):
    budget_item = models.ForeignKey(StaffBudgetItem, on_delete=models.CASCADE)
    eligible_employment = models.CharField(max_length=50, choices=EmploymentCategories)

class OverheadBudgetItem(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.project.acronym} - Overhead - {self.amount}"

class OtherBudgetItem(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    short_title = models.CharField(max_length=50, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.project.acronym} - {self.title} - {self.amount}"
    
    def get_transactions(self, year: int = None) -> list['OtherBudgetItemTransaction']:
        if year:
            return list(OtherBudgetItemTransaction.objects.filter(budget_item=self, date__year=year))
        return list(OtherBudgetItemTransaction.objects.filter(budget_item=self))

class OtherBudgetItemTransaction(models.Model):
    budget_item = models.ForeignKey(OtherBudgetItem, on_delete=models.CASCADE)
    date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    sap_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.budget_item} - {self.date} - {self.amount}"

controlling/views.py
from decimal import Decimal
from .utils import render

from projects.models import Project
from staffing.models import StaffMember
from django.utils import timezone

from projects.checks import full_checks as projects_full_checks
from staffing.checks import full_checks as staffing_full_checks

# Create your views here.
def main(request):
    projects_full_checks(request)
    staffing_full_checks(request)

    projects = Project.objects.filter(end_date__gt=timezone.now()).order_by('start_date')
    staff = StaffMember.objects.all()

    budgets_per_year = {}
    for project in projects:
        months = (project.end_date.year - project.start_date.year) * 12 + (project.end_date.month - project.start_date.month + 1)

        budgets_per_year.setdefault(str(project.start_date.year), {})[project.acronym] = (project.budget_total * (12 - project.start_date.month) / months).quantize(Decimal('0.01'))
        for year in range(project.start_date.year + 1, project.end_date.year):
            budgets_per_year.setdefault(str(year), {})[project.acronym] = (12 * project.budget_total / months).quantize(Decimal('0.01'))
        budgets_per_year.setdefault(str(project.end_date.year), {})[project.acronym] = (project.budget_total * project.end_date.month / months).quantize(Decimal('0.01'))

    for key, value in budgets_per_year.items():
        budgets_per_year[key]["total"] = sum(value.values())

    return render(request, "controlling/main.html", {"projects": projects, "staff_list": staff, "budgets_per_year": budgets_per_year})

controlling/templates/controlling/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GroupPlanning{% endblock %}</title>

    {% bootstrap_css %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary d-print-none">
        <div class="container-fluid">
            <a class="navbar-brand mx-2" href="/">Group Planning</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownProjects" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Projekte
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownProjects">
                            {% for project in group_projects %}
                                <a class="dropdown-item" href="{% url 'projects:details' project.acronym %}">{{ project.acronym }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownStaff" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mitarbeiter
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownStaff">
                            {% for staff in group_staff %}
                                <a class="dropdown-item" href="{% url 'staffing:details' staff.id %}">{{ staff }}</a>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="text-center mt-4">
            <h1 class="display-5 fw-bold text-body-emphasis">{% block heading %}Group Planning{% endblock %}</h1>
        </div>

        {% bootstrap_messages %}

        {% block content %}{% endblock %}

    </div>

    {% bootstrap_javascript %}
</body>
</html>

controlling/templates/controlling/main.html
{% extends "controlling/base.html" %}

{% block title %}Research Group Planning Tool{% endblock %}
{% block heading %}Research Group Planning Tool{% endblock %}

{% block content %}

<h2 class="mt-2">Laufende und geplante Projekte</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Laufzeit</th>
            <th scope="col">Budget</th>
            <th scope="col">Personalbudgets</th>
            <th scope="col">Andere Budgets</th>
            <th scope="col">Overhead</th>
        </tr>
    </thead>
    <tbody>
        {% for project in projects %}
            <tr>
                <th scope="row"><a href="{% url 'projects:details' project.acronym %}">{{ project.acronym }}</a></th>
                <td>{{ project.start_date }} - {{ project.end_date }}</td>
                <td>€ {{ project.budget_total }}</td>
                <td>
                    {% for budget in project.staffbudgetitem_set.all %}
                        <div>{{ budget.short_title }}: € {{ budget.amount }}</div>
                    {% endfor %}
                </td>
                <td>
                    {% for budget in project.otherbudgetitem_set.all %}
                        <div>{{ budget.short_title }}: € {{ budget.amount }}</div>
                    {% endfor %}
                </td>
                <td>
                    {% for budget in project.overheadbudgetitem_set.all %}
                        <div>€ {{ budget.amount }}</div>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['timeline']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var container = document.getElementById('timeline_projects');
        var chart = new google.visualization.Timeline(container);
        var dataTable = new google.visualization.DataTable();

        dataTable.addColumn({ type: 'string', id: 'Project' });
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });

        // Example data: [Employee, Project, Start, End]
        dataTable.addRows([
{% for project in projects %}
            [ '{{ project.acronym }}', new Date("{{ project.start_date.isoformat }}"), new Date("{{ project.end_date.isoformat }}") ],
{% endfor %}
        ]);
        // Dynamically set chart height based on number of rows
        var rowCount = dataTable.getNumberOfRows();
        container.style.height = (rowCount * 45 + 47) + 'px'; 

        var options = {
            timeline: { showRowLabels: true, showBarLabels: false },
            hAxis: {
                format: 'MMM yyyy',
                minorGridlines: { count: 12 },
                majorGridlines: { count: 2 },
           }
        };

        chart.draw(dataTable, options);
    }
</script>
<div id="timeline_projects" style="height: 500px;"></div>

<h2 class="mt-2">Jahresscheiben</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            {% for year in budgets_per_year %}
                <th scope="col">{{ year }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
            <tr>
                <th scope="col">allokiert</th>
                {% for year, data in budgets_per_year.items %}
                    <td>€ {{ data.total }}</td>
                {% endfor %}
            </tr>
    </tbody>
</table>

<h2 class="mt-2">Mitarbeitende</h2>

<table>
    <thead>
        <tr>
            <td>Name</td>
        </tr>
    </thead>
    <tbody>
        {% for staff in staff_list %}
            <tr>
                <td><a href="{% url 'staffing:details' staff.id %}">{{ staff }}</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}